name: "Commands"

on:
  push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - name: logging
      run: |
        echo "::group::My group message"
        echo Msg 1
        echo Msg 2
        echo "::endgroup::"
    - name: setup env
      run: |
        echo "MY_VAL=hello" >> $GITHUB_ENV
    - name: printing var
      run: |
        echo "$MY_VAL"